gestion/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import DetailView

from gestion.models.animal import Animal
from gestion.models.consultation import Consultation
from gestion.models.person import Person
from gestion.views import home, animal, person, consultation
from gestion.views.person import export_new_clients_emails, toggle_person_status
from gestion.views.animal import toggle_animal_status

urlpatterns = [
    path("", home, name="accueil"),
    # Animaux
    path("animals/", animal.animal_list, name="animals"),
    path("animals/create", animal.CreateAnimal.as_view(), name="create_animal"),
    path("animals/update/<int:pk>/", animal.UpdateAnimal.as_view(), name="update_animal"),
    path(
        "animals/<int:pk>/",
        login_required(
            DetailView.as_view(
                model=Animal,
                template_name="gestion/animal/animal_detail.html",
            )
        ),
        name="detail_animal",
    ),
    path("animals/medical_info/update/<int:pk>/", animal.UpdateMedicalInfo.as_view(), name="update_medical_info"),
    # Consultations
    path("consultations/", consultation.search_consultation, name="consultations"),
    path("consultations/create/<int:pk>/", consultation.create_consultation, name="create_consultation"),
    path("consultations/update/<int:pk>/", consultation.UpdateConsultation.as_view(), name="update_consultation"),
    path(
        "consultations/<int:pk>/",
        login_required(
            DetailView.as_view(
                model=Consultation,
                template_name="gestion/consultation/consultation_detail.html",
            )
        ),
        name="detail_consultation",
    ),

    # Propriétaires
    path("persons/", person.person_list, name="persons"),
    path("persons/create", person.CreatePerson.as_view(), name="create_person"),
    path("persons/update/<int:pk>/", person.UpdatePerson.as_view(), name="update_person"),
    path(
        "persons/<int:pk>/",
        login_required(
            DetailView.as_view(
                model=Person,
                template_name="gestion/person/person_detail.html",
            )
        ),
        name="detail_person",
    ),
    path('export-new-clients/', export_new_clients_emails, name='export_new_clients_emails'),
    path('animal/toggle-status/<int:pk>/', toggle_animal_status, name='toggle_animal_status'),
    path('person/toggle-status/<int:pk>/', toggle_person_status, name='toggle_person_status'),
]

osteopathe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="accueil")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path("gestion/", include("gestion.urls")),
]

gestion/models/animal.py
from enum import Enum
from datetime import date

from django.db import models

from gestion.models import OuiNonChoice
from gestion.models.person import Person


class AnimalTypeChoice(Enum):
    CHIEN = "Chien"
    CHAT = "Chat"
    CHEVAL = "Cheval"
    LAPIN = "Lapin"
    COCHON_INDE = "Cochon d'inde"
    CHEVRE = "Chèvre"
    MOUTON = "Mouton"
    REPTILE = "Reptile"


class SexChoice(Enum):
    F = "Femelle"
    M = "Mâle"


class OriginChoice(Enum):
    REFUGE = "Refuge"
    ELEVAGE = "Elevage"
    PARTICULIER = "Particulier"
    ANIMALERIE = "Animalerie"
    DIVAGATION = "Divagation"


class MedicalInfo(models.Model):
    last_consult_date = models.DateField(verbose_name="Date de dernière consultation ostéopathique", null=True, blank=True)
    vaccinated = models.CharField(
        max_length=3,
        verbose_name="Vacciné(e)",
        choices=[(tag.name, tag.value) for tag in OuiNonChoice],
    )
    ape_api = models.CharField(
        max_length=3,
        verbose_name="Traité(e) APE/API",
        choices=[(tag.name, tag.value) for tag in OuiNonChoice],
    )
    antecedents = models.TextField(verbose_name="Antécédents médicaux", max_length=1000, blank=True)
    surgeries = models.TextField(verbose_name="Chirurgie(s)", max_length=300, blank=True)
    locomotor_disorders = models.CharField(verbose_name="Troubles locomoteurs", max_length=300, blank=True)
    treatments = models.TextField(verbose_name="Traitements", max_length=300, blank=True)
    behaviour = models.CharField(verbose_name="Comportement", max_length=300, blank=True)
    other = models.CharField(verbose_name="Autres", max_length=300, blank=True)


class Animal(models.Model):
    update_date = models.DateField(verbose_name="Date de mise à jour", auto_now=True)
    name = models.CharField(verbose_name="Nom", max_length=150)
    race = models.CharField(verbose_name="Race", max_length=150, blank=True)
    living_place = models.CharField(verbose_name="Lieu de vie", max_length=300, blank=True)
    food = models.CharField(verbose_name="Alimentation", max_length=300, blank=True)
    activities = models.CharField(verbose_name="Activité(s)", max_length=300, blank=True)
    origin = models.CharField(verbose_name="Lieu d'adoption",
        max_length=50,
        choices=[(tag.name, tag.value) for tag in OriginChoice],
    )
    comment = models.TextField(verbose_name="Commentaire", blank=True, max_length=200)
    birth_date = models.DateField(verbose_name="Date de naissance", null=True, blank=True)
    adoption_age = models.CharField(verbose_name="Age d'adoption", max_length=50, blank=True)
    sex = models.CharField( verbose_name="Sexe",
        max_length=30,
        choices=[(tag.name, tag.value) for tag in SexChoice],
    )
    type = models.CharField(
        max_length=30,
        verbose_name="Espèce",
        choices=[(tag.name, tag.value) for tag in AnimalTypeChoice],
    )
    sterilised = models.CharField(
        max_length=3,
        verbose_name="Stérilisé(e)",
        choices=[(tag.name, tag.value) for tag in OuiNonChoice],
    )
    proprietaire = models.ForeignKey(
        Person,
        verbose_name="Propriétaire",
        on_delete=models.PROTECT,
    )
    # Uniquement pour les chevaux
    meadow_address = models.CharField(verbose_name="Adresse du pré", max_length=300, blank=True)
    medical_info = models.OneToOneField(MedicalInfo, on_delete=models.PROTECT)
    inactif = models.BooleanField(default=False)

    def get_age(self):
        if not self.birth_date:
            return "Âge non renseigné"
        today = date.today()
        delta = today - self.birth_date
        years = delta.days // 365
        months = (delta.days % 365) // 30
        if years < 1:
            return f"{months} mois"
        elif months == 0:
            return f"{years} an" if years == 1 else f"{years} ans"
        else:
            return f"{years} ans et {months} mois"

    def save(self, *args, **kwargs):
        # Initialisation des infos de santé à la création
        if self._state.adding:
            info = MedicalInfo.objects.create()
            self.medical_info = info
        return super(Animal, self).save(*args, **kwargs)

gestion/models/consultation.py
from django.db import models
from enum import Enum


class Consultation(models.Model):
    LIEU_CHOICES = [
        ("DOMICILE", "Domicile"),
        ("CABINET", "Cabinet"),
        ("ECURIE", "Écurie"),
    ]

    date = models.DateField()
    date_accident = models.DateField(
        verbose_name="Date de l’accident ou de l’apparition des symptômes",
        null=True, blank=True
    )
    reason = models.CharField(verbose_name="Motif de Consultation", max_length=300, blank=True)
    symptoms_duration = models.CharField(verbose_name="Durée des symptômes", max_length=100, blank=True)
    summary = models.TextField(verbose_name="Bilan ostéopathique", max_length=500, blank=True)
    comments = models.CharField(verbose_name="Commentaires", max_length=500, blank=True)
    animal = models.ForeignKey(
        'gestion.Animal',
        verbose_name="Animal",
        on_delete=models.PROTECT,
    )
    lieu = models.CharField(
        max_length=30,
        choices=LIEU_CHOICES,
        blank=True,
        null=True,
        verbose_name="Lieu de Consultation"
    )

    def display_lieu(self):
        return dict(self.LIEU_CHOICES).get(self.lieu, "")

    def __str__(self):
        return "Consultation du " + self.date.strftime("%d/%m/%Y")

gestion/forms/animal.py
from django.db.models import BLANK_CHOICE_DASH
from django.forms import ModelForm, Form, CharField, ChoiceField, Select, BooleanField

from gestion.models.animal import Animal, MedicalInfo, AnimalTypeChoice
from gestion.models.person import Person


class AnimalSearchForm(Form):
    name = CharField(max_length=150, required=False, label="Nom")
    type = ChoiceField(
        choices=BLANK_CHOICE_DASH + [(tag.name, tag.value) for tag in AnimalTypeChoice],
        widget=Select(),
        required=False,
    )
    race = CharField(max_length=150, required=False, label="Race")
    show_inactive = BooleanField(required=False, label="Afficher les éléments désactivés")


class AnimalForm(ModelForm):
    # Pour mettre les champs obligatoires en gras
    required_css_class = 'required'
    class Meta:
        model = Animal
        fields = (
            "proprietaire",
            "name",
            "sex",
            "type",
            "race",
            "living_place",
            "food",
            "activities",
            "comment",
            "origin",
            "birth_date",
            "adoption_age",
            "sterilised",
            "meadow_address",
        )

    def __init__(self, *args, **kwargs):
        super(AnimalForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget.attrs['class'] = 'datePicker'
        self.fields["proprietaire"].queryset = Person.objects.order_by('last_name')


class MedicalInfoForm(ModelForm):
    # Pour mettre les champs obligatoires en gras
    required_css_class = 'required'
    class Meta:
        model = MedicalInfo
        fields = (
            "last_consult_date",
            "vaccinated",
            "ape_api",
            "antecedents",
            "surgeries",
            "locomotor_disorders",
            "treatments",
            "behaviour",
            "other",
        )

    def __init__(self, *args, **kwargs):
        super(MedicalInfoForm, self).__init__(*args, **kwargs)
        self.fields['last_consult_date'].widget.attrs['class'] = 'datePicker'

gestion/forms/animals.py
from django.forms import ModelForm

from gestion.models.animal import Animal


class AnimalCreateForm(ModelForm):
    # Pour mettre les champs obligatoires en gras
    required_css_class = 'required'
    class Meta:
        model = Animal
        fields = (
            "name",
            "sex",
            "type",
            "race",
            "living_place",
            "food",
            "activities",
            "origin",
            "birth_date",
            "adoption_age",
            "sterilised",
            "identification",
            "meadow_address",
        )

    def __init__(self, *args, **kwargs):
        super(AnimalCreateForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget.attrs['class'] = 'datePicker'

gestion/forms/home.py
from django import forms
from datetime import date, timedelta

class ConsultationStatsForm(forms.Form):
    start_date = forms.DateField(
        label="Date de début",
        initial=date.today() - timedelta(days=365),
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    end_date = forms.DateField(
        label="Date de fin",
        initial=date.today,
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    detail_type = forms.ChoiceField(
        label="Type de détail",
        choices=[
            ("animal_type", "Type d’animal"),
            ("lieu", "Lieu de consultation")
        ],
        initial="animal_type"
    )
    scale = forms.ChoiceField(
        label="Échelle",
        choices=[
            ("month", "Mois"),
            ("week", "Semaine"),
            ("day", "Jour")
        ],
        initial="month"
    )

gestion/views/animal.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from gestion.forms.animal import AnimalForm, MedicalInfoForm, AnimalSearchForm
from gestion.models.animal import Animal, MedicalInfo
from gestion.models.person import Person


@login_required()
def animal_list(request):
    animals = Animal.objects.filter(inactif=False)
    selected = "animals"
    title = "Liste des animaux"
    # Pagination : 20 éléments par page
    if request.method == "POST":
        form = AnimalSearchForm(request.POST)
        if form.is_valid():
            base_url = reverse('animals')
            query_string = form.data.urlencode()
            url = '{}?{}'.format(base_url, query_string)
            return redirect(url)
    else:
        form = AnimalSearchForm()
        name_form = request.GET.get("name", "")
        race_form = request.GET.get("race", "")
        type_form = request.GET.get("type", "")
        show_inactive = request.GET.get("show_inactive", "off") == "on"
        if show_inactive:
            animals = Animal.objects.all()
        if name_form:
            form.fields["name"].initial = name_form
            animals = animals.filter(name__icontains=name_form)
        if race_form:
            form.fields["race"].initial = race_form
            animals = animals.filter(race__icontains=race_form)
        if type_form:
            form.fields["type"].initial = type_form
            animals = animals.filter(type=type_form)
    paginator = Paginator(animals.order_by("-update_date"), 20)
    try:
        page = request.GET.get("page")
        if not page:
            page = 1
        animal_list = paginator.page(page)
    except EmptyPage:
        # Si on dépasse la limite de pages, on prend la dernière
        animal_list = paginator.page(paginator.num_pages())

    return render(request, "gestion/animal/animal_list.html", locals())


class CreateAnimal(LoginRequiredMixin, CreateView):
    model = Animal
    form_class = AnimalForm
    template_name = "gestion/animal/animal_form.html"

    def get_success_url(self):
        return reverse_lazy("detail_animal", kwargs={"pk": self.object.id})

    def get_context_data(self, **kwargs):
        context = super(CreateAnimal, self).get_context_data(**kwargs)
        context['title'] = "Créer un animal"
        return context

    def get_form(self, form_class=None):
        form = CreateView.get_form(self, form_class=form_class)
        id_proprietaire = self.request.GET.get("proprietaire", "")
        if id_proprietaire:
            proprietaire = Person.objects.get(id=id_proprietaire)
            form.fields["proprietaire"].initial = proprietaire
        return form


class UpdateAnimal(LoginRequiredMixin, UpdateView):
    model = Animal
    form_class = AnimalForm
    template_name = "gestion/animal/animal_form.html"

    def get_success_url(self):
        return reverse_lazy("detail_animal", kwargs={"pk": self.object.id})

    def get_context_data(self, **kwargs):
        context = super(UpdateAnimal, self).get_context_data(**kwargs)
        context['title'] = "Mettre à jour " + str(self.object.name)
        return context


class UpdateMedicalInfo(LoginRequiredMixin, UpdateView):
    model = MedicalInfo
    form_class = MedicalInfoForm
    template_name = "gestion/animal/medical_info_form.html"

    def get_success_url(self):
        return reverse_lazy("detail_animal", kwargs={"pk": self.object.animal.id})

    def get_context_data(self, **kwargs):
        context = super(UpdateMedicalInfo, self).get_context_data(**kwargs)
        context['title'] = "Mettre à jour " + str(self.object.animal.name)
        return context

@login_required
@csrf_exempt
def toggle_animal_status(request, pk):
    try:
        animal = Animal.objects.get(pk=pk)
        animal.inactif = not animal.inactif
        animal.save()
        return JsonResponse({"success": True, "inactif": animal.inactif})
    except Animal.DoesNotExist:
        return JsonResponse({"success": False, "error": "Animal introuvable"}, status=404)

gestion/views/animals.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from gestion.forms.animals import AnimalCreateForm
from gestion.models.animal import Animal


@login_required()
def animal_list(request):
    animals = Animal.objects.all()
    selected = "animals"
    title = "Liste des animaux"
    # Pagination : 20 éléments par page
    paginator = Paginator(animals.order_by("-update_date"), 20)
    try:
        page = request.GET.get("page")
        if not page:
            page = 1
        animal_list = paginator.page(page)
    except EmptyPage:
        # Si on dépasse la limite de pages, on prend la dernière
        animal_list = paginator.page(paginator.num_pages())

    return render(request, "gestion/animal/animal_list.html", locals())

class CreateAnimal(LoginRequiredMixin, CreateView):
    model = Animal
    form_class = AnimalCreateForm
    template_name = "gestion/animal/animal_create_form.html"

    def get_success_url(self):
        return reverse_lazy("animals")

    def get_context_data(self, **kwargs):
        context = super(CreateAnimal, self).get_context_data(**kwargs)
        context['title'] = "Créer un animal"
        return context

templates/gestion/animal/animal_create_form.html
{% extends "gestion/base.html" %}
{% block content %}
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <br/>
    <div class="row">
        <div class="col">
            <a href = "{% url 'animals' %}"  class="btn btn-secondary">Annuler</a>
        </div>
        <div class="col">
            <input class="btn btn-info" type="submit" />
        </div>
    </div>
</form>
{% endblock %}

templates/gestion/animal/animal_detail.html
{% extends "gestion/base.html" %}
{% block content %}
<div class="row p-4">
    <div class="col-sm-12 mt-3">
        <div class="card">
            <div class="card-header">
                Informations générales
                <a href= "{% url 'update_animal' animal.id %}" class="close">
                    <i class="fas fa-pen"></i>
                </a>
                </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <strong> Propriétaire </strong> :
                        <a href = "{% url 'detail_person' animal.proprietaire.id %}">
                            {{animal.proprietaire}}
                        </a><br>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-sm-12">
                        <strong> Statut </strong> :
                        <span id="status-badge" class="badge {% if animal.inactif %}badge-danger{% else %}badge-success{% endif %}">
                            {% if animal.inactif %}Inactif{% else %}Actif{% endif %}
                        </span>
                        <button
                            id="toggle-status-btn"
                            class="btn btn-sm btn-outline-primary ml-3"
                            data-url="{% url 'toggle_animal_status' animal.id %}"
                        >
                            Activation/Désactivation
                        </button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Nom </strong> : {{animal.name}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Sexe </strong> : {{animal.get_sex_display}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Âge </strong> : {{animal.get_age}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Type </strong> : {{animal.get_type_display}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Race </strong> : {{animal.race}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Date de naissance </strong> : {{animal.birth_date|date:'d F Y'|default:" - "}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Lieu de vie </strong> : {{animal.living_place}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Alimentation </strong> : {{animal.food}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Activités </strong> : {{animal.activities}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Lieu d'adoption </strong> :  {{ animal.get_origin_display }} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Age d'adoption </strong> : {{animal.adoption_age}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Stérilisé </strong> :  {{ animal.get_sterilised_display }} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <strong> Commentaire général </strong> :  {{ animal.comment }} <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row p-4">
    <div class="col-sm-12 mt-3">
        <div class="card">
            <div class="card-header">
                Informations médicales
                <a href= "{% url 'update_medical_info' animal.medical_info.id %}" class="close">
                    <i class="fas fa-pen"></i>
                </a>
                </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Date de dernière consultation ostéopathique </strong>
                        : {{animal.medical_info.last_consult_date|default:" - "}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Vacciné(e) </strong>
                        : {{animal.medical_info.get_vaccinated_display}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Traité(e) APE/API </strong>
                        : {{animal.medical_info.get_ape_api_display}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Antécédents médicaux </strong>
                        : {{animal.medical_info.antecedents}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Chirurgie(s) </strong>
                        : {{animal.medical_info.surgeries}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Troubles locomoteurs </strong>
                        : {{animal.medical_info.locomotor_disorders}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <strong> Traitements </strong>
                        : {{animal.medical_info.treatments}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Comportement </strong>
                        : {{animal.medical_info.behaviour}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Autres </strong>
                        :  {{ animal.medical_info.other }} <br>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="row p-4">
    <div class="col-sm-12 mt-3">
        <div class="card">
            <div class="card-header">
                Liste des consultations
            </div>
            <div class="table-responsive-sm p-4">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th scope="col">Date</th>
                            <th scope="col">Motif de Consultation</th>
                            <th scope="col">Bilan ostéopathique</th>
                            <th scope="col">Commentaires</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for consultation in animal.consultation_set.all %}
                        <tr class="table-info">
                            <td>
                                <a href = "{% url 'detail_consultation' consultation.id %}">
                                    {{consultation.date|default:" - "}}
                                </a>
                            </td>
                            <td>{{consultation.reason}}</td>
                            <td>{{consultation.summary}}</td>
                            <td>{{consultation.comments}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="text-right">
    <a href= "{% url 'create_consultation' animal.id %}" class="btn btn-info">Ajouter une consultation</a>
</div>

<script>
    document.getElementById("toggle-status-btn").addEventListener("click", function (e) {
        e.preventDefault();
        const url = this.getAttribute("data-url");
        if (confirm("Êtes-vous sûr de vouloir basculer le statut ?")) {
            fetch(url, {
                method: "POST",
                headers: {
                    "X-CSRFToken": "{{ csrf_token }}",
                    "Content-Type": "application/json",
                },
            })
            .then(response => {
                if (!response.ok) {
                    throw new Error("Erreur lors de la requête.");
                }
                return response.json();
            })
            .then(data => {
                const badge = document.getElementById("status-badge");
                if (data.inactif) {
                    badge.textContent = "Inactif";
                    badge.className = "badge badge-danger";
                } else {
                    badge.textContent = "Actif";
                    badge.className = "badge badge-success";
                }
            })
            .catch(error => {
                console.error("Erreur :", error);
                alert("Une erreur est survenue.");
            });
        }
    });
</script>

{% endblock %}

templates/gestion/animal/animal_form.html
{% extends "gestion/base.html" %}
{% block content %}
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <br/>
    <div class="row">
        <div class="col">
            {% if object %}
            <a href = "{% url 'detail_animal' object.id %}"  class="btn btn-secondary">Annuler</a>
   		    {% else %}
   			<a href = "{% url 'animals' %}"  class="btn btn-secondary">Annuler</a>
   		    {% endif %}
        </div>
        <div class="col">
            <input class="btn btn-info" type="submit" />
        </div>
    </div>
</form>
{% endblock %}

templates/gestion/animal/animal_list.html
{% extends "gestion/base.html" %}
{% load tag %}
{% block content %}

<div class="row p-4">
    <div class="col-sm-12 mt-3">
        <div class="card">
            <div class="card-header">
                Recherche
            </div>
		<form action = "{% url 'animals' %}" method="post">
            <div class="card-body">
                {%csrf_token %}
                <div class="row">
                    <div class="col-sm-4">
                        {{ form.name.label_tag }}
                    </div>
                    <div class="col-sm-8">
                        {{ form.name }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        {{ form.race.label_tag }}
                    </div>
                    <div class="col-sm-8">
                        {{ form.race }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
		    		    {{ form.type.label_tag }}
                    </div>
                    <div class="col-sm-8">
                        {{ form.type }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm4">
                        {{ form.show_inactive.label_tag }}
                    </div>
                    <div class="col-sm-8">
                        {{ form.show_inactive }}
                    </div>
                </div>

                <div class="text-right">
                    <button class="btn btn-info" type="submit"> <i class="fa fa-search" aria-hidden="true"></i> Rechercher</button>
                </div>
            </div>
        </form>
        </div>
    </div>
</div>
<div class="table-responsive-sm p-4">
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Nom</th>
            <th scope="col">Type</th>
            <th scope="col">Sexe</th>
            <th scope="col">Race</th>
            <th scope="col">Âge</th>
        </tr>
        </thead>
        <tbody>
        {% for animal in animal_list %}
        <tr class="table-info">
            <td><a href= "{% url 'detail_animal' animal.id %}">{{animal.name}}</a></td>
            <td>{{animal.get_type_display}}</td>
            <td>{{animal.get_sex_display}}</td>
            <td>{{animal.race}}</td>
            <td>{{animal.get_age}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        {% if animal_list.has_previous %}
        <a href="?{% param_replace page=animal_list.previous_page_number%}">Précédente</a> -
        {% endif %}

        <span class="current">
            Page {{ animal_list.number }} sur {{ animal_list.paginator.num_pages }}
        </span>

        {% if animal_list.has_next %}
        - <a href="?{% param_replace page=animal_list.next_page_number%}">Suivante</a>
        {% endif %}
    </div>
</div>
<div class="text-right">
    <a href= "{% url 'create_animal' %}" class="btn btn-info">Ajouter un animal</a>
</div>

{% endblock %}