gestion/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import DetailView

from gestion.models.animal import Animal
from gestion.models.consultation import Consultation
from gestion.models.person import Person
from gestion.views import home, animal, person, consultation
from gestion.views.person import export_new_clients_emails, toggle_person_status
from gestion.views.animal import toggle_animal_status

urlpatterns = [
    path("", home, name="accueil"),
    # Animaux
    path("animals/", animal.animal_list, name="animals"),
    path("animals/create", animal.CreateAnimal.as_view(), name="create_animal"),
    path("animals/update/<int:pk>/", animal.UpdateAnimal.as_view(), name="update_animal"),
    path(
        "animals/<int:pk>/",
        login_required(
            DetailView.as_view(
                model=Animal,
                template_name="gestion/animal/animal_detail.html",
            )
        ),
        name="detail_animal",
    ),
    path("animals/medical_info/update/<int:pk>/", animal.UpdateMedicalInfo.as_view(), name="update_medical_info"),
    # Consultations
    path("consultations/", consultation.search_consultation, name="consultations"),
    path("consultations/create/<int:pk>/", consultation.create_consultation, name="create_consultation"),
    path("consultations/update/<int:pk>/", consultation.UpdateConsultation.as_view(), name="update_consultation"),
    path(
        "consultations/<int:pk>/",
        login_required(
            DetailView.as_view(
                model=Consultation,
                template_name="gestion/consultation/consultation_detail.html",
            )
        ),
        name="detail_consultation",
    ),

    # Propriétaires
    path("persons/", person.person_list, name="persons"),
    path("persons/create", person.CreatePerson.as_view(), name="create_person"),
    path("persons/update/<int:pk>/", person.UpdatePerson.as_view(), name="update_person"),
    path(
        "persons/<int:pk>/",
        login_required(
            DetailView.as_view(
                model=Person,
                template_name="gestion/person/person_detail.html",
            )
        ),
        name="detail_person",
    ),
    path('export-new-clients/', export_new_clients_emails, name='export_new_clients_emails'),
    path('animal/toggle-status/<int:pk>/', toggle_animal_status, name='toggle_animal_status'),
    path('person/toggle-status/<int:pk>/', toggle_person_status, name='toggle_person_status'),
]

osteopathe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="accueil")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path("gestion/", include("gestion.urls")),
]

gestion/models/consultation.py
from django.db import models
from enum import Enum


class Consultation(models.Model):
    LIEU_CHOICES = [
        ("DOMICILE", "Domicile"),
        ("CABINET", "Cabinet"),
        ("ECURIE", "Écurie"),
    ]

    date = models.DateField()
    date_accident = models.DateField(
        verbose_name="Date de l’accident ou de l’apparition des symptômes",
        null=True, blank=True
    )
    reason = models.CharField(verbose_name="Motif de Consultation", max_length=300, blank=True)
    symptoms_duration = models.CharField(verbose_name="Durée des symptômes", max_length=100, blank=True)
    summary = models.TextField(verbose_name="Bilan ostéopathique", max_length=500, blank=True)
    comments = models.CharField(verbose_name="Commentaires", max_length=500, blank=True)
    animal = models.ForeignKey(
        'gestion.Animal',
        verbose_name="Animal",
        on_delete=models.PROTECT,
    )
    lieu = models.CharField(
        max_length=30,
        choices=LIEU_CHOICES,
        blank=True,
        null=True,
        verbose_name="Lieu de Consultation"
    )

    def display_lieu(self):
        return dict(self.LIEU_CHOICES).get(self.lieu, "")

    def __str__(self):
        return "Consultation du " + self.date.strftime("%d/%m/%Y")

gestion/forms/animal.py
from django.db.models import BLANK_CHOICE_DASH
from django.forms import ModelForm, Form, CharField, ChoiceField, Select, BooleanField

from gestion.models.animal import Animal, MedicalInfo, AnimalTypeChoice
from gestion.models.person import Person


class AnimalSearchForm(Form):
    name = CharField(max_length=150, required=False, label="Nom")
    type = ChoiceField(
        choices=BLANK_CHOICE_DASH + [(tag.name, tag.value) for tag in AnimalTypeChoice],
        widget=Select(),
        required=False,
    )
    race = CharField(max_length=150, required=False, label="Race")
    show_inactive = BooleanField(required=False, label="Afficher les éléments désactivés")


class AnimalForm(ModelForm):
    # Pour mettre les champs obligatoires en gras
    required_css_class = 'required'
    class Meta:
        model = Animal
        fields = (
            "proprietaire",
            "name",
            "sex",
            "type",
            "race",
            "living_place",
            "food",
            "activities",
            "comment",
            "origin",
            "birth_date",
            "adoption_age",
            "sterilised",
            "meadow_address",
        )

    def __init__(self, *args, **kwargs):
        super(AnimalForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget.attrs['class'] = 'datePicker'
        self.fields["proprietaire"].queryset = Person.objects.order_by('last_name')


class MedicalInfoForm(ModelForm):
    # Pour mettre les champs obligatoires en gras
    required_css_class = 'required'
    class Meta:
        model = MedicalInfo
        fields = (
            "last_consult_date",
            "vaccinated",
            "ape_api",
            "antecedents",
            "surgeries",
            "locomotor_disorders",
            "treatments",
            "behaviour",
            "other",
        )

    def __init__(self, *args, **kwargs):
        super(MedicalInfoForm, self).__init__(*args, **kwargs)
        self.fields['last_consult_date'].widget.attrs['class'] = 'datePicker'

gestion/forms/animals.py
from django.forms import ModelForm

from gestion.models.animal import Animal


class AnimalCreateForm(ModelForm):
    # Pour mettre les champs obligatoires en gras
    required_css_class = 'required'
    class Meta:
        model = Animal
        fields = (
            "name",
            "sex",
            "type",
            "race",
            "living_place",
            "food",
            "activities",
            "origin",
            "birth_date",
            "adoption_age",
            "sterilised",
            "identification",
            "meadow_address",
        )

    def __init__(self, *args, **kwargs):
        super(AnimalCreateForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget.attrs['class'] = 'datePicker'

gestion/views/animal.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from gestion.forms.animal import AnimalForm, MedicalInfoForm, AnimalSearchForm
from gestion.models.animal import Animal, MedicalInfo
from gestion.models.person import Person


@login_required()
def animal_list(request):
    animals = Animal.objects.filter(inactif=False)
    selected = "animals"
    title = "Liste des animaux"
    # Pagination : 20 éléments par page
    if request.method == "POST":
        form = AnimalSearchForm(request.POST)
        if form.is_valid():
            base_url = reverse('animals')
            query_string = form.data.urlencode()
            url = '{}?{}'.format(base_url, query_string)
            return redirect(url)
    else:
        form = AnimalSearchForm()
        name_form = request.GET.get("name", "")
        race_form = request.GET.get("race", "")
        type_form = request.GET.get("type", "")
        show_inactive = request.GET.get("show_inactive", "off") == "on"
        if show_inactive:
            animals = Animal.objects.all()
        if name_form:
            form.fields["name"].initial = name_form
            animals = animals.filter(name__icontains=name_form)
        if race_form:
            form.fields["race"].initial = race_form
            animals = animals.filter(race__icontains=race_form)
        if type_form:
            form.fields["type"].initial = type_form
            animals = animals.filter(type=type_form)
    paginator = Paginator(animals.order_by("-update_date"), 20)
    try:
        page = request.GET.get("page")
        if not page:
            page = 1
        animal_list = paginator.page(page)
    except EmptyPage:
        # Si on dépasse la limite de pages, on prend la dernière
        animal_list = paginator.page(paginator.num_pages())

    return render(request, "gestion/animal/animal_list.html", locals())


class CreateAnimal(LoginRequiredMixin, CreateView):
    model = Animal
    form_class = AnimalForm
    template_name = "gestion/animal/animal_form.html"

    def get_success_url(self):
        return reverse_lazy("detail_animal", kwargs={"pk": self.object.id})

    def get_context_data(self, **kwargs):
        context = super(CreateAnimal, self).get_context_data(**kwargs)
        context['title'] = "Créer un animal"
        return context

    def get_form(self, form_class=None):
        form = CreateView.get_form(self, form_class=form_class)
        id_proprietaire = self.request.GET.get("proprietaire", "")
        if id_proprietaire:
            proprietaire = Person.objects.get(id=id_proprietaire)
            form.fields["proprietaire"].initial = proprietaire
        return form


class UpdateAnimal(LoginRequiredMixin, UpdateView):
    model = Animal
    form_class = AnimalForm
    template_name = "gestion/animal/animal_form.html"

    def get_success_url(self):
        return reverse_lazy("detail_animal", kwargs={"pk": self.object.id})

    def get_context_data(self, **kwargs):
        context = super(UpdateAnimal, self).get_context_data(**kwargs)
        context['title'] = "Mettre à jour " + str(self.object.name)
        return context


class UpdateMedicalInfo(LoginRequiredMixin, UpdateView):
    model = MedicalInfo
    form_class = MedicalInfoForm
    template_name = "gestion/animal/medical_info_form.html"

    def get_success_url(self):
        return reverse_lazy("detail_animal", kwargs={"pk": self.object.animal.id})

    def get_context_data(self, **kwargs):
        context = super(UpdateMedicalInfo, self).get_context_data(**kwargs)
        context['title'] = "Mettre à jour " + str(self.object.animal.name)
        return context

@login_required
@csrf_exempt
def toggle_animal_status(request, pk):
    try:
        animal = Animal.objects.get(pk=pk)
        animal.inactif = not animal.inactif
        animal.save()
        return JsonResponse({"success": True, "inactif": animal.inactif})
    except Animal.DoesNotExist:
        return JsonResponse({"success": False, "error": "Animal introuvable"}, status=404)

gestion/views/animals.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from gestion.forms.animals import AnimalCreateForm
from gestion.models.animal import Animal


@login_required()
def animal_list(request):
    animals = Animal.objects.all()
    selected = "animals"
    title = "Liste des animaux"
    # Pagination : 20 éléments par page
    paginator = Paginator(animals.order_by("-update_date"), 20)
    try:
        page = request.GET.get("page")
        if not page:
            page = 1
        animal_list = paginator.page(page)
    except EmptyPage:
        # Si on dépasse la limite de pages, on prend la dernière
        animal_list = paginator.page(paginator.num_pages())

    return render(request, "gestion/animal/animal_list.html", locals())

class CreateAnimal(LoginRequiredMixin, CreateView):
    model = Animal
    form_class = AnimalCreateForm
    template_name = "gestion/animal/animal_create_form.html"

    def get_success_url(self):
        return reverse_lazy("animals")

    def get_context_data(self, **kwargs):
        context = super(CreateAnimal, self).get_context_data(**kwargs)
        context['title'] = "Créer un animal"
        return context

gestion/views/consultation.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.dateparse import parse_date
from django.views.generic import CreateView, UpdateView
from django.db.models import Func, CharField
from django.db.models.functions import Lower

from gestion.forms.consultation import ConsultationForm, ConsultationSearchForm
from gestion.models.animal import Animal
from gestion.models.consultation import Consultation

from unicodedata import normalize

@login_required()
def search_consultation(request):
    consultations = Consultation.objects.all()
    selected = "consultations"
    title = "Liste des consulations"

    if request.method == "POST":
        form = ConsultationSearchForm(request.POST)
        if form.is_valid():
            base_url = reverse('consultations')
            query_string = form.data.urlencode()
            url = '{}?{}'.format(base_url, query_string)
            return redirect(url)
    else:
        form = ConsultationSearchForm()
        date_min_form = request.GET.get("date_min", "")
        date_max_form = request.GET.get("date_max", "")
        animal_form = request.GET.get("animal", "")
        lieu_form = request.GET.get("lieu", "")
        type_animal_form = request.GET.get("type_animal", "")
        motif_form = request.GET.get("motif", "")
        if date_min_form:
            form.fields["date_min"].initial = date_min_form
            consultations = consultations.filter(date__gte=parse_date(date_min_form))
        if date_max_form:
            form.fields["date_max"].initial = date_max_form
            consultations = consultations.filter(date__lte=parse_date(date_max_form))
        if animal_form:
            form.fields["animal"].initial = animal_form
            consultations = consultations.filter(animal__name__icontains=animal_form)
        if lieu_form:
            form.fields["lieu"].initial = lieu_form
            consultations = consultations.filter(lieu=lieu_form)
        if type_animal_form:
            form.fields["type_animal"].initial = type_animal_form
            consultations = consultations.filter(animal__type=type_animal_form)
        if motif_form:
            form.fields["motif"].initial = motif_form
            normalized_motif = normalize("NFKD", motif_form).encode("ascii", "ignore").decode("utf-8").lower()
            consultations = consultations.annotate(
                motif_clean=Lower("reason")
            ).filter(motif_clean__icontains=normalized_motif)

        # Pagination : 20 éléments par page
        paginator = Paginator(consultations.order_by("-date"), 20)
        nb_results = consultations.count()
        try:
            page = request.GET.get("page")
            if not page:
                page = 1
            consultation_list = paginator.page(page)
        except EmptyPage:
            # Si on dépasse la limite de pages, on prend la dernière
            consultation_list = paginator.page(paginator.num_pages())

        return render(request, "gestion/consultation/consultation_list.html", locals())


@login_required
def create_consultation(request, pk):
    animal = Animal.objects.get(id=pk)
    title = "Créer une consultation pour " + animal.name
    if request.method == "POST":
        form = ConsultationForm(data = request.POST)
        if form.is_valid():
            consultation = form.save(commit=False)
            consultation.animal = animal
            consultation.save()
            return redirect("detail_consultation", pk=consultation.id)
    else :
        form = ConsultationForm()

    return render(request, "gestion/consultation/consultation_form.html", locals())


class UpdateConsultation(LoginRequiredMixin, UpdateView):
    model = Consultation
    form_class = ConsultationForm
    template_name = "gestion/consultation/consultation_form.html"

    def get_success_url(self):
        return reverse_lazy("detail_consultation", kwargs={"pk": self.object.animal.id})

    def get_context_data(self, **kwargs):
        context = super(UpdateConsultation, self).get_context_data(**kwargs)
        context['title'] = "Mettre à jour une consultation de " + str(self.object.animal.name)
        return context

class Unaccent(Func):
    function = "unaccent"
    output_field = CharField()

templates/gestion/consultation/consultation_detail.html
{% extends "gestion/base.html" %}
{% block content %}
<div class="row p-4">
    <div class="col-sm-12 mt-3">
        <div class="card">
            <div class="card-header">
                Consultation du {{consultation.date}}
                <a href= "{% url 'update_consultation' consultation.id %}" class="close">
                    <i class="fas fa-pen"></i>
                </a>
                </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Animal concerné </strong> :
                        <a href = "{% url 'detail_animal' consultation.animal.id %}">
                            {{consultation.animal.name}}
                        </a> <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Propriétaire </strong> :
                        <a href = "{% url 'detail_person' consultation.animal.proprietaire.id %}">
                            {{consultation.animal.proprietaire}}
                        </a> <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Motif de Consultation </strong>
                        : {{consultation.reason}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Date de l’accident ou de l’apparition des symptômes </strong>
                        : {{consultation.date_accident|default:"-"}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Durée des symptômes </strong>
                        : {{consultation.symptoms_duration}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <strong> Bilan ostéopathique </strong> : {{consultation.summary}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <strong> Lieu de Consultation </strong> : {{consultation.get_lieu_display|default:" "}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <strong> Commentaires </strong> : {{consultation.comments}} <br>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/gestion/consultation/consultation_form.html
{% extends "gestion/base.html" %}
{% block content %}
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <br/>
    <div class="row">
        <div class="col">
            {% if object %}
            <a href = "{% url 'detail_consultation' object.id %}"  class="btn btn-secondary">Annuler</a>
   		    {% else %}
   			<a href = "{% url 'animals' %}"  class="btn btn-secondary">Annuler</a>
   		    {% endif %}
        </div>
        <div class="col">
            <input class="btn btn-info" type="submit" />
        </div>
    </div>
</form>
{% endblock %}

templates/gestion/consultation/consultation_list.html
{% extends "gestion/base.html" %}
{% load tag %}
{% block content %}

<div class="row p-4">
    <div class="col-sm-12 mt-3">
        <div class="card">
            <div class="card-header">
                Recherche
            </div>
		<form action = "{% url 'consultations' %}" method="post">
            <div class="card-body">
                {%csrf_token %}
                <div class="row">
                    <div class="col-md-8">
                        {{ form.date_min.label_tag }} {{ form.date_min }}
                    </div>
                    <div class="col-md-4">
                        {{ form.date_max.label_tag }} {{ form.date_max }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
		    		    {{ form.animal.label_tag }}
                    </div>
                    <div class="col-sm-8">
                        {{ form.animal }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
		    		    {{ form.lieu.label_tag }}
                    </div>
                    <div class="col-sm-8">
                        {{ form.lieu }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        {{ form.type_animal.label_tag }}
                    </div>
                    <div class="col-sm-8">
                        {{ form.type_animal }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        {{ form.motif.label_tag }}
                    </div>
                    <div class="col-sm-8">
                        {{ form.motif }}
                    </div>
                </div>
                <div class="text-right">
                    <button class="btn btn-info" type="submit"> <i class="fa fa-search" aria-hidden="true"></i> Rechercher</button>
                </div>
            </div>
        </form>
        </div>
    </div>
</div>
{{nb_results}} résultat(s)
<div class="table-responsive-sm p-4">
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Consultation</th>
            <th scope="col">Animal</th>
            <th scope="col">Motif</th>
            <th scope="col">Lieu</th>
        </tr>
        </thead>
        <tbody>
        {% for consult in consultation_list %}
        <tr class="table-info">
            <td><a href= "{% url 'detail_consultation' consult.id %}">{{consult}}</a></td>
            <td><a href= "{% url 'detail_animal' consult.animal.id %}">{{consult.animal.name}}</a></td>
            <td>{{consult.reason}}</td>
            <td>{{consult.get_lieu_display|default:" "}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        {% if consultation_list.has_previous %}
        <a href="?{% param_replace page=consultation_list.previous_page_number%}">Précédente</a> -
        {% endif %}

        <span class="current">
            Page {{ consultation_list.number }} sur {{ consultation_list.paginator.num_pages }}
        </span>

        {% if consultation_list.has_next %}
        - <a href="?{% param_replace page=consultation_list.next_page_number%}">Suivante</a>
        {% endif %}
    </div>
</div>

{% endblock %}