gestion/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import DetailView

from gestion.models.animal import Animal
from gestion.models.consultation import Consultation
from gestion.models.person import Person
from gestion.views import home, animal, person, consultation
from gestion.views.person import export_new_clients_emails, toggle_person_status
from gestion.views.animal import toggle_animal_status

urlpatterns = [
    path("", home, name="accueil"),
    # Animaux
    path("animals/", animal.animal_list, name="animals"),
    path("animals/create", animal.CreateAnimal.as_view(), name="create_animal"),
    path("animals/update/<int:pk>/", animal.UpdateAnimal.as_view(), name="update_animal"),
    path(
        "animals/<int:pk>/",
        login_required(
            DetailView.as_view(
                model=Animal,
                template_name="gestion/animal/animal_detail.html",
            )
        ),
        name="detail_animal",
    ),
    path("animals/medical_info/update/<int:pk>/", animal.UpdateMedicalInfo.as_view(), name="update_medical_info"),
    # Consultations
    path("consultations/", consultation.search_consultation, name="consultations"),
    path("consultations/create/<int:pk>/", consultation.create_consultation, name="create_consultation"),
    path("consultations/update/<int:pk>/", consultation.UpdateConsultation.as_view(), name="update_consultation"),
    path(
        "consultations/<int:pk>/",
        login_required(
            DetailView.as_view(
                model=Consultation,
                template_name="gestion/consultation/consultation_detail.html",
            )
        ),
        name="detail_consultation",
    ),

    # Propriétaires
    path("persons/", person.person_list, name="persons"),
    path("persons/create", person.CreatePerson.as_view(), name="create_person"),
    path("persons/update/<int:pk>/", person.UpdatePerson.as_view(), name="update_person"),
    path(
        "persons/<int:pk>/",
        login_required(
            DetailView.as_view(
                model=Person,
                template_name="gestion/person/person_detail.html",
            )
        ),
        name="detail_person",
    ),
    path('export-new-clients/', export_new_clients_emails, name='export_new_clients_emails'),
    path('animal/toggle-status/<int:pk>/', toggle_animal_status, name='toggle_animal_status'),
    path('person/toggle-status/<int:pk>/', toggle_person_status, name='toggle_person_status'),
]

osteopathe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="accueil")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path("gestion/", include("gestion.urls")),
]

gestion/models/animal.py
from enum import Enum
from datetime import date

from django.db import models

from gestion.models import OuiNonChoice
from gestion.models.person import Person


class AnimalTypeChoice(Enum):
    CHIEN = "Chien"
    CHAT = "Chat"
    CHEVAL = "Cheval"
    LAPIN = "Lapin"
    COCHON_INDE = "Cochon d'inde"
    CHEVRE = "Chèvre"
    MOUTON = "Mouton"
    REPTILE = "Reptile"


class SexChoice(Enum):
    F = "Femelle"
    M = "Mâle"


class OriginChoice(Enum):
    REFUGE = "Refuge"
    ELEVAGE = "Elevage"
    PARTICULIER = "Particulier"
    ANIMALERIE = "Animalerie"
    DIVAGATION = "Divagation"


class MedicalInfo(models.Model):
    last_consult_date = models.DateField(verbose_name="Date de dernière consultation ostéopathique", null=True, blank=True)
    vaccinated = models.CharField(
        max_length=3,
        verbose_name="Vacciné(e)",
        choices=[(tag.name, tag.value) for tag in OuiNonChoice],
    )
    ape_api = models.CharField(
        max_length=3,
        verbose_name="Traité(e) APE/API",
        choices=[(tag.name, tag.value) for tag in OuiNonChoice],
    )
    antecedents = models.TextField(verbose_name="Antécédents médicaux", max_length=1000, blank=True)
    surgeries = models.TextField(verbose_name="Chirurgie(s)", max_length=300, blank=True)
    locomotor_disorders = models.CharField(verbose_name="Troubles locomoteurs", max_length=300, blank=True)
    treatments = models.TextField(verbose_name="Traitements", max_length=300, blank=True)
    behaviour = models.CharField(verbose_name="Comportement", max_length=300, blank=True)
    other = models.CharField(verbose_name="Autres", max_length=300, blank=True)


class Animal(models.Model):
    update_date = models.DateField(verbose_name="Date de mise à jour", auto_now=True)
    name = models.CharField(verbose_name="Nom", max_length=150)
    race = models.CharField(verbose_name="Race", max_length=150, blank=True)
    living_place = models.CharField(verbose_name="Lieu de vie", max_length=300, blank=True)
    food = models.CharField(verbose_name="Alimentation", max_length=300, blank=True)
    activities = models.CharField(verbose_name="Activité(s)", max_length=300, blank=True)
    origin = models.CharField(verbose_name="Lieu d'adoption",
        max_length=50,
        choices=[(tag.name, tag.value) for tag in OriginChoice],
    )
    comment = models.TextField(verbose_name="Commentaire", blank=True, max_length=200)
    birth_date = models.DateField(verbose_name="Date de naissance", null=True, blank=True)
    adoption_age = models.CharField(verbose_name="Age d'adoption", max_length=50, blank=True)
    sex = models.CharField( verbose_name="Sexe",
        max_length=30,
        choices=[(tag.name, tag.value) for tag in SexChoice],
    )
    type = models.CharField(
        max_length=30,
        verbose_name="Espèce",
        choices=[(tag.name, tag.value) for tag in AnimalTypeChoice],
    )
    sterilised = models.CharField(
        max_length=3,
        verbose_name="Stérilisé(e)",
        choices=[(tag.name, tag.value) for tag in OuiNonChoice],
    )
    proprietaire = models.ForeignKey(
        Person,
        verbose_name="Propriétaire",
        on_delete=models.PROTECT,
    )
    # Uniquement pour les chevaux
    meadow_address = models.CharField(verbose_name="Adresse du pré", max_length=300, blank=True)
    medical_info = models.OneToOneField(MedicalInfo, on_delete=models.PROTECT)
    inactif = models.BooleanField(default=False)

    def get_age(self):
        if not self.birth_date:
            return "Âge non renseigné"
        today = date.today()
        delta = today - self.birth_date
        years = delta.days // 365
        months = (delta.days % 365) // 30
        if years < 1:
            return f"{months} mois"
        elif months == 0:
            return f"{years} an" if years == 1 else f"{years} ans"
        else:
            return f"{years} ans et {months} mois"

    def save(self, *args, **kwargs):
        # Initialisation des infos de santé à la création
        if self._state.adding:
            info = MedicalInfo.objects.create()
            self.medical_info = info
        return super(Animal, self).save(*args, **kwargs)

gestion/views/animal.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from gestion.forms.animal import AnimalForm, MedicalInfoForm, AnimalSearchForm
from gestion.models.animal import Animal, MedicalInfo
from gestion.models.person import Person


@login_required()
def animal_list(request):
    animals = Animal.objects.filter(inactif=False)
    selected = "animals"
    title = "Liste des animaux"
    # Pagination : 20 éléments par page
    if request.method == "POST":
        form = AnimalSearchForm(request.POST)
        if form.is_valid():
            base_url = reverse('animals')
            query_string = form.data.urlencode()
            url = '{}?{}'.format(base_url, query_string)
            return redirect(url)
    else:
        form = AnimalSearchForm()
        name_form = request.GET.get("name", "")
        race_form = request.GET.get("race", "")
        type_form = request.GET.get("type", "")
        show_inactive = request.GET.get("show_inactive", "off") == "on"
        if show_inactive:
            animals = Animal.objects.all()
        if name_form:
            form.fields["name"].initial = name_form
            animals = animals.filter(name__icontains=name_form)
        if race_form:
            form.fields["race"].initial = race_form
            animals = animals.filter(race__icontains=race_form)
        if type_form:
            form.fields["type"].initial = type_form
            animals = animals.filter(type=type_form)
    paginator = Paginator(animals.order_by("-update_date"), 20)
    try:
        page = request.GET.get("page")
        if not page:
            page = 1
        animal_list = paginator.page(page)
    except EmptyPage:
        # Si on dépasse la limite de pages, on prend la dernière
        animal_list = paginator.page(paginator.num_pages())

    return render(request, "gestion/animal/animal_list.html", locals())


class CreateAnimal(LoginRequiredMixin, CreateView):
    model = Animal
    form_class = AnimalForm
    template_name = "gestion/animal/animal_form.html"

    def get_success_url(self):
        return reverse_lazy("detail_animal", kwargs={"pk": self.object.id})

    def get_context_data(self, **kwargs):
        context = super(CreateAnimal, self).get_context_data(**kwargs)
        context['title'] = "Créer un animal"
        return context

    def get_form(self, form_class=None):
        form = CreateView.get_form(self, form_class=form_class)
        id_proprietaire = self.request.GET.get("proprietaire", "")
        if id_proprietaire:
            proprietaire = Person.objects.get(id=id_proprietaire)
            form.fields["proprietaire"].initial = proprietaire
        return form


class UpdateAnimal(LoginRequiredMixin, UpdateView):
    model = Animal
    form_class = AnimalForm
    template_name = "gestion/animal/animal_form.html"

    def get_success_url(self):
        return reverse_lazy("detail_animal", kwargs={"pk": self.object.id})

    def get_context_data(self, **kwargs):
        context = super(UpdateAnimal, self).get_context_data(**kwargs)
        context['title'] = "Mettre à jour " + str(self.object.name)
        return context


class UpdateMedicalInfo(LoginRequiredMixin, UpdateView):
    model = MedicalInfo
    form_class = MedicalInfoForm
    template_name = "gestion/animal/medical_info_form.html"

    def get_success_url(self):
        return reverse_lazy("detail_animal", kwargs={"pk": self.object.animal.id})

    def get_context_data(self, **kwargs):
        context = super(UpdateMedicalInfo, self).get_context_data(**kwargs)
        context['title'] = "Mettre à jour " + str(self.object.animal.name)
        return context

@login_required
@csrf_exempt
def toggle_animal_status(request, pk):
    try:
        animal = Animal.objects.get(pk=pk)
        animal.inactif = not animal.inactif
        animal.save()
        return JsonResponse({"success": True, "inactif": animal.inactif})
    except Animal.DoesNotExist:
        return JsonResponse({"success": False, "error": "Animal introuvable"}, status=404)

gestion/views/animals.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from gestion.forms.animals import AnimalCreateForm
from gestion.models.animal import Animal


@login_required()
def animal_list(request):
    animals = Animal.objects.all()
    selected = "animals"
    title = "Liste des animaux"
    # Pagination : 20 éléments par page
    paginator = Paginator(animals.order_by("-update_date"), 20)
    try:
        page = request.GET.get("page")
        if not page:
            page = 1
        animal_list = paginator.page(page)
    except EmptyPage:
        # Si on dépasse la limite de pages, on prend la dernière
        animal_list = paginator.page(paginator.num_pages())

    return render(request, "gestion/animal/animal_list.html", locals())

class CreateAnimal(LoginRequiredMixin, CreateView):
    model = Animal
    form_class = AnimalCreateForm
    template_name = "gestion/animal/animal_create_form.html"

    def get_success_url(self):
        return reverse_lazy("animals")

    def get_context_data(self, **kwargs):
        context = super(CreateAnimal, self).get_context_data(**kwargs)
        context['title'] = "Créer un animal"
        return context

gestion/views/consultation.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.dateparse import parse_date
from django.views.generic import CreateView, UpdateView
from django.db.models import Func, CharField
from django.db.models.functions import Lower

from gestion.forms.consultation import ConsultationForm, ConsultationSearchForm
from gestion.models.animal import Animal
from gestion.models.consultation import Consultation

from unicodedata import normalize

@login_required()
def search_consultation(request):
    consultations = Consultation.objects.all()
    selected = "consultations"
    title = "Liste des consulations"

    if request.method == "POST":
        form = ConsultationSearchForm(request.POST)
        if form.is_valid():
            base_url = reverse('consultations')
            query_string = form.data.urlencode()
            url = '{}?{}'.format(base_url, query_string)
            return redirect(url)
    else:
        form = ConsultationSearchForm()
        date_min_form = request.GET.get("date_min", "")
        date_max_form = request.GET.get("date_max", "")
        animal_form = request.GET.get("animal", "")
        lieu_form = request.GET.get("lieu", "")
        type_animal_form = request.GET.get("type_animal", "")
        motif_form = request.GET.get("motif", "")
        if date_min_form:
            form.fields["date_min"].initial = date_min_form
            consultations = consultations.filter(date__gte=parse_date(date_min_form))
        if date_max_form:
            form.fields["date_max"].initial = date_max_form
            consultations = consultations.filter(date__lte=parse_date(date_max_form))
        if animal_form:
            form.fields["animal"].initial = animal_form
            consultations = consultations.filter(animal__name__icontains=animal_form)
        if lieu_form:
            form.fields["lieu"].initial = lieu_form
            consultations = consultations.filter(lieu=lieu_form)
        if type_animal_form:
            form.fields["type_animal"].initial = type_animal_form
            consultations = consultations.filter(animal__type=type_animal_form)
        if motif_form:
            form.fields["motif"].initial = motif_form
            normalized_motif = normalize("NFKD", motif_form).encode("ascii", "ignore").decode("utf-8").lower()
            consultations = consultations.annotate(
                motif_clean=Lower("reason")
            ).filter(motif_clean__icontains=normalized_motif)

        # Pagination : 20 éléments par page
        paginator = Paginator(consultations.order_by("-date"), 20)
        nb_results = consultations.count()
        try:
            page = request.GET.get("page")
            if not page:
                page = 1
            consultation_list = paginator.page(page)
        except EmptyPage:
            # Si on dépasse la limite de pages, on prend la dernière
            consultation_list = paginator.page(paginator.num_pages())

        return render(request, "gestion/consultation/consultation_list.html", locals())


@login_required
def create_consultation(request, pk):
    animal = Animal.objects.get(id=pk)
    title = "Créer une consultation pour " + animal.name
    if request.method == "POST":
        form = ConsultationForm(data = request.POST)
        if form.is_valid():
            consultation = form.save(commit=False)
            consultation.animal = animal
            consultation.save()
            return redirect("detail_consultation", pk=consultation.id)
    else :
        form = ConsultationForm()

    return render(request, "gestion/consultation/consultation_form.html", locals())


class UpdateConsultation(LoginRequiredMixin, UpdateView):
    model = Consultation
    form_class = ConsultationForm
    template_name = "gestion/consultation/consultation_form.html"

    def get_success_url(self):
        return reverse_lazy("detail_consultation", kwargs={"pk": self.object.animal.id})

    def get_context_data(self, **kwargs):
        context = super(UpdateConsultation, self).get_context_data(**kwargs)
        context['title'] = "Mettre à jour une consultation de " + str(self.object.animal.name)
        return context

class Unaccent(Func):
    function = "unaccent"
    output_field = CharField()

templates/gestion/person/person_detail.html
{% extends "gestion/base.html" %}
{% block content %}
<div class="row p-4">
    <div class="col-sm-12 mt-3">
        <div class="card">
            <div class="card-header">
                Coordonnées
                <a href= "{% url 'update_person' person.id %}" class="close">
                    <i class="fas fa-pen"></i>
                </a>
                </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Prénom </strong> : {{person.first_name}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Nom </strong> : {{person.last_name}} <br>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-sm-12">
                        <strong> Statut </strong> :
                        <span id="status-badge" class="badge {% if person.inactif %}badge-danger{% else %}badge-success{% endif %}">
                            {% if person.inactif %}Inactif{% else %}Actif{% endif %}
                        </span>
                        <button
                            id="toggle-status-btn"
                            class="btn btn-sm btn-outline-primary ml-3"
                            data-url="{% url 'toggle_person_status' person.id %}"
                        >
                            Activation/Désactivation
                        </button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <strong> Email </strong> : {{person.email}} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Téléphone </strong> : {{person.telephone}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <strong> Adresse </strong> : {{person.get_complete_address}} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <strong> Commentaire </strong> : {{person.commentaire}} <br>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-sm-6">
                        <strong> Date de première consultation </strong> :
                        {{ person.get_first_consultation_date|date:"d/m/Y"|default:" - " }} <br>
                    </div>
                    <div class="col-sm-6">
                        <strong> Date de dernière consultation </strong> :
                        {{ person.get_last_consultation_date|date:"d/m/Y"|default:" - " }} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <strong> Nombre de consultations </strong> :
                        {{ person.get_total_consultations }} <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <strong> Professionnel du monde animalier </strong> :
                        {{ person.professionnel_monde_animalier|default:"Non spécifié" }} <br>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="row p-4">
    <div class="col-sm-12 mt-3">
        <div class="card">
            <div class="card-header">
                Liste des animaux
            </div>
            <div class="table-responsive-sm p-4">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th scope="col">Nom</th>
                            <th scope="col">Type</th>
                            <th scope="col">Sexe</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for animal in person.animal_set.all %}
                        <tr class="table-info">
                            <td><a href = "{% url 'detail_animal' animal.id %}"> {{animal.name}}</a></td>
                            <td>{{animal.get_type_display}}</td>
                            <td>{{animal.get_sex_display}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="text-right">
    <a href= "{% url 'create_animal' %}?proprietaire={{person.id}}" class="btn btn-info">Ajouter animal</a>
</div>

<script>
    document.getElementById("toggle-status-btn").addEventListener("click", function (e) {
        e.preventDefault();
        const url = this.getAttribute("data-url");
        if (confirm("Êtes-vous sûr de vouloir basculer le statut ?")) {
            fetch(url, {
                method: "POST",
                headers: {
                    "X-CSRFToken": "{{ csrf_token }}",
                    "Content-Type": "application/json",
                },
            })
            .then(response => {
                if (!response.ok) {
                    throw new Error("Erreur lors de la requête.");
                }
                return response.json();
            })
            .then(data => {
                const badge = document.getElementById("status-badge");
                if (data.inactif) {
                    badge.textContent = "Inactif";
                    badge.className = "badge badge-danger";
                } else {
                    badge.textContent = "Actif";
                    badge.className = "badge badge-success";
                }
            })
            .catch(error => {
                console.error("Erreur :", error);
                alert("Une erreur est survenue.");
            });
        }
    });
</script>


{% endblock %}

templates/gestion/person/person_form.html
{% extends "gestion/base.html" %}
{% block content %}
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <br/>
    <div class="row">
        <div class="col">
            {% if object %}
            <a href = "{% url 'detail_person' object.id %}"  class="btn btn-secondary">Annuler</a>
   		    {% else %}
   			<a href = "{% url 'persons' %}"  class="btn btn-secondary">Annuler</a>
   		    {% endif %}
        </div>
        <div class="col">
            <input class="btn btn-info" type="submit" />
        </div>
    </div>
</form>
{% endblock %}

templates/gestion/person/person_list.html
{% extends "gestion/base.html" %}
{% load tag %}
{% block content %}

<div class="row p-4">
    <div class="col-sm-12 mt-3">
        <div class="card">
            <div class="card-header">
                Recherche
                <div class="text-right">
                    <a href="{% url 'export_new_clients_emails' %}" class="btn btn-success">
                        Exporter les nouveaux clients
                    </a>
                </div>
            </div>
		<form action = "{% url 'persons' %}" method="post">
            <div class="card-body">
                {%csrf_token %}
                <div class="row">
                    <div class="col-sm-2">
                        {{ form.last_name.label_tag }}
                    </div>
                    <div class="col-sm-10">
                        {{ form.last_name }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
		    		    {{ form.city.label_tag }}
                    </div>
                    <div class="col-md-10">
                        {{ form.city }}
                    </div>
                </div>
                <div class="row mt-3">
            <div class="col-sm-2">
                {{ form.postal_code.label_tag }}
            </div>
            <div class="col-sm-10">
                {{ form.postal_code }}
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-sm-2">
                {{ form.telephone.label_tag }}
            </div>
            <div class="col-sm-10">
                {{ form.telephone }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm4">
                {{ form.show_inactive.label_tag }}
            </div>
            <div class="col-sm-8">
                {{ form.show_inactive }}
            </div>
        </div>
                <div class="text-right">
                    <button class="btn btn-info" type="submit"> <i class="fa fa-search" aria-hidden="true"></i> Rechercher</button>
                </div>
            </div>
        </form>
        </div>
    </div>
</div>
<div class="table-responsive-sm p-4">
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Mail</th>
                <th scope="col">Téléphone</th>
                <th scope="col">Adresse</th>
            </tr>
        </thead>
        <tbody>
        {% for person in person_list %}
        <tr class="table-info">
            <td><a href= "{% url 'detail_person' person.id %}">{{person.last_name}}</a></td>
            <td>{{person.first_name}}</td>
            <td>{{person.email}}</td>
            <td>{{person.telephone}}</td>
            <td>{{person.get_complete_address}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        {% if person_list.has_previous %}
        <a href="?{% param_replace page=person_list.previous_page_number%}">Précédente</a> -
        {% endif %}

        <span class="current">
            Page {{ person_list.number }} sur {{ person_list.paginator.num_pages }}
        </span>

        {% if person_list.has_next %}
        - <a href="?{% param_replace page=person_list.next_page_number%}">Suivante</a>
        {% endif %}
    </div>
</div>
<div class="text-right">
    <a href= "{% url 'create_person' %}" class="btn btn-info">Ajouter un Propriétaire</a>
</div>

{% endblock %}